# Generated by Django 2.2.24 on 2022-03-15 12:19

from django.db import migrations


def load_flats(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for owner in Owner.objects.all():
        apartments_flats = Flat.objects.filter(owner=owner.owner)
        owner.flats.set(apartments_flats)




class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20220315_1056'),
    ]

    operations = [
        migrations.RunPython(load_flats),
    ]
